[wokwi]
version = 1
elf = "firmware.elf"
firmware = "firmware.bin"
gdbServerPort = 3333

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"
